[workspace]
members = [ 
    "crates/pyrev_ast", 
    "crates/pyrev_ast_derive", 
    "crates/pyrev_ast_build", 
    "crates/pyrev_ast_visit", 
    "crates/pyrev_core", 
    "crates/pyrev_query", 
    "crates/pyrev_query_inner", 
    "crates/pyrev_parser", 
    "crates/pyrev_decompiler",
    "crates/pyrev_marshal",
    "crates/pyrev_object",
    "crates/pyrev_app",
    "crates/pyrev_plugin",
    "crates/pyrev_plugin_macro", 
    "plugins/pyrev_pyc",
    "plugins/pyrev_pyc_macro",
    "plugins/pyrev_pyinstaller",
]

[package]
name = "pyrev"
authors = ["hacbit <hacbit@foxmail.com>"]
version = "1.2.0-alpha"
edition = "2021"
description = "A Python bytecode reverse engineering tool."
build = "build.rs"
license = "MIT"

[dependencies]
pyrev_app = { path = "crates/pyrev_app" }
pyrev_pyc = { path = "plugins/pyrev_pyc" }
pyrev_pyinstaller = { path = "plugins/pyrev_pyinstaller" }

[profile.dev]
# Uncomment the following lines to allow clippy to break your build.
# rustflags = ["-D", "warnings"]
panic = "unwind"
lto = true
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = 3

[features]
