[package]
name = "pyrev_ast"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyrev_ast_derive = { path = "../pyrev_ast_derive" }
pyrev_query_inner = { path = "../pyrev_query_inner" }
regex = "1.10.2"