[package]
name = "pyrev_internal"
version = "1.2.0-alpha"
edition = "2021"

[dependencies]
pyrev_app = { path = "../pyrev_app" }
pyrev_ast = { path = "../pyrev_ast" }
pyrev_ast_build = { path = "../pyrev_ast_build" }
pyrev_ast_visit = { path = "../pyrev_ast_visit" }
pyrev_core = { path = "../pyrev_core" }
pyrev_decompiler = { path = "../pyrev_decompiler" }
pyrev_log = { path = "../pyrev_log" }
pyrev_marshal = { path = "../pyrev_marshal" }
pyrev_object = { path = "../pyrev_object" }
pyrev_parser = { path = "../pyrev_parser" }
pyrev_plugin = { path = "../pyrev_plugin" }
pyrev_query = { path = "../pyrev_query" }
