[package]
name = "pyrev_app"
version = "1.2.0-alpha"
edition = "2021"

[dependencies]
atty = "0.2.14"
pyrev_app_macro = { path = "../pyrev_app_macro" }

[dependencies.clap]
version = "4.5.1"
features = ["derive", "cargo"]

[dependencies.pyrev_core]
path = "../pyrev_core"

[dependencies.pyrev_query]
path = "../pyrev_query"