[package]
name = "pyrev_core"
version = "1.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
colored = "2.0.4"
lazy_format = "2.0.0"
lazy_static = "1.4.0"
regex = "1.10.2"

[dependencies.pyrev_ast]
path = "../pyrev_ast"
